CREATE TABLE audit_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, occurred_at TIMESTAMPTZ NOT NULL,
 operation_id TEXT NOT NULL, tool TEXT NOT NULL, outcome TEXT NOT NULL, event JSONB NOT NULL
);
CREATE INDEX audit_operation ON audit_events(operation_id,id);
CREATE TABLE admin (
 singleton SMALLINT PRIMARY KEY CHECK(singleton=1),
 username TEXT NOT NULL, password_hash BYTEA NOT NULL, version TEXT NOT NULL
);
CREATE TABLE admin_sessions (
 digest BYTEA PRIMARY KEY CHECK(octet_length(digest)=32),
 admin_version TEXT NOT NULL, expires_at BIGINT NOT NULL
);
CREATE INDEX sessions_expiry ON admin_sessions(expires_at);
