package storage

import (
	"context"
	"encoding/hex"
	"errors"

	"github.com/wentf9/xops-cli/core/mcp/ports"
	"github.com/wentf9/xops-mcp/internal/naming"
)

// MCPToken separates a credential ID from its stable client identity. Secrets
// are generated by the server and never retained; only a SHA-256 digest is stored.
type MCPToken struct {
	ID        string `json:"id"`
	ClientID  string `json:"clientID"`
	Name      string `json:"name"`
	Prefix    string `json:"prefix"`
	Version   uint64 `json:"version"`
	Enabled   bool   `json:"enabled"`
	CreatedAt int64  `json:"createdAt"`
	ExpiresAt int64  `json:"expiresAt"`
	RevokedAt int64  `json:"revokedAt"`
}

// MCPTokenRecord is storage-only. APIs must return MCPToken, never this record.
type MCPTokenRecord struct {
	Token  MCPToken
	Digest string
}

// MaxMCPTokenTime is the last Unix second representable in a four-digit year.
const MaxMCPTokenTime int64 = 253402300799

func (v MCPTokenRecord) Validate() error {
	digest, err := hex.DecodeString(v.Digest)
	t := v.Token
	if err != nil || len(digest) != 32 || hex.EncodeToString(digest) != v.Digest ||
		t.ID == "" || len(t.ID) > 128 || t.ClientID == "" || len(t.ClientID) > 128 ||
		len(t.Prefix) > 32 || t.Version == 0 || t.Version >= 1<<63 || t.CreatedAt <= 0 ||
		t.ExpiresAt < 0 || t.ExpiresAt > MaxMCPTokenTime || t.RevokedAt < 0 || t.RevokedAt > 0 && t.Enabled || naming.Validate(t.Name) != nil {
		return errors.New("invalid MCP token record")
	}
	return nil
}

type MCPTokenRepository interface {
	MCPTokens(context.Context) ([]MCPTokenRecord, error)
	MCPTokenByDigest(context.Context, string) (MCPTokenRecord, error)
	SaveMCPToken(context.Context, uint64, MCPTokenRecord, ports.AuditEvent) error
}
