package storage

import (
	"context"
	"encoding/hex"
	"errors"
	"slices"
	"strings"
	"unicode"

	"github.com/wentf9/xops-cli/core/mcp/ports"
	"github.com/wentf9/xops-mcp/internal/naming"
)

// MCPToken separates a credential ID from its stable client identity. Secrets
// are generated by the server and never retained; only a SHA-256 digest is stored.
type MCPToken struct {
	ID        string   `json:"id"`
	ClientID  string   `json:"clientID"`
	Name      string   `json:"name"`
	Prefix    string   `json:"prefix"`
	Version   uint64   `json:"version"`
	Enabled   bool     `json:"enabled"`
	CreatedAt int64    `json:"createdAt"`
	ExpiresAt int64    `json:"expiresAt"`
	RevokedAt int64    `json:"revokedAt"`
	NodeScope string   `json:"nodeScope"`
	NodeIDs   []string `json:"nodeIDs"`
}

const (
	MCPTokenNodeScopeAll      = "all"
	MCPTokenNodeScopeSelected = "selected"
	MaxMCPTokenNodeIDs        = 10000
)

var ErrInvalidMCPTokenScope = errors.New("invalid MCP token node scope")

// NormalizeNodeScope validates the node restriction and gives equivalent scopes
// a deterministic representation without changing a caller-owned ID slice.
func (t *MCPToken) NormalizeNodeScope() error {
	if t.NodeScope == "" {
		t.NodeScope = MCPTokenNodeScopeAll
	}
	if t.NodeScope != MCPTokenNodeScopeAll && t.NodeScope != MCPTokenNodeScopeSelected ||
		len(t.NodeIDs) > MaxMCPTokenNodeIDs || t.NodeScope == MCPTokenNodeScopeAll && len(t.NodeIDs) != 0 {
		return ErrInvalidMCPTokenScope
	}
	ids := append([]string{}, t.NodeIDs...)
	slices.Sort(ids)
	for i, id := range ids {
		if id == "" || len(id) > 128 || strings.ContainsFunc(id, func(r rune) bool { return unicode.IsSpace(r) || unicode.IsControl(r) }) || i > 0 && id == ids[i-1] {
			return ErrInvalidMCPTokenScope
		}
	}
	t.NodeIDs = ids
	return nil
}

// MCPTokenRecord is storage-only. APIs must return MCPToken, never this record.
type MCPTokenRecord struct {
	Token  MCPToken
	Digest string
}

// MaxMCPTokenTime is the last Unix second representable in a four-digit year.
const MaxMCPTokenTime int64 = 253402300799

func (v MCPTokenRecord) Validate() error {
	digest, err := hex.DecodeString(v.Digest)
	t := v.Token
	if err := t.NormalizeNodeScope(); err != nil {
		return err
	}
	if err != nil || len(digest) != 32 || hex.EncodeToString(digest) != v.Digest ||
		t.ID == "" || len(t.ID) > 128 || t.ClientID == "" || len(t.ClientID) > 128 ||
		len(t.Prefix) > 32 || t.Version == 0 || t.Version >= 1<<63 || t.CreatedAt <= 0 ||
		t.ExpiresAt < 0 || t.ExpiresAt > MaxMCPTokenTime || t.RevokedAt < 0 || t.RevokedAt > 0 && t.Enabled || naming.Validate(t.Name) != nil {
		return errors.New("invalid MCP token record")
	}
	return nil
}

type MCPTokenRepository interface {
	MCPTokens(context.Context) ([]MCPTokenRecord, error)
	MCPTokenByDigest(context.Context, string) (MCPTokenRecord, error)
	MCPTokenByID(context.Context, string) (MCPTokenRecord, error)
	MCPTokenByClientID(context.Context, string) (MCPTokenRecord, error)
	SaveMCPToken(context.Context, uint64, MCPTokenRecord, ports.AuditEvent) error
}
